version: '2'

services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=P05tgr3s/pw
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - db:docker_postgres_db
    depends_on:
      - db
