version: '2'

services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=P05tgr3s/pw
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    links:
      - db:docker_postgres_db
    volumes:
      - .:/home/node
    environment:
      - PGPASSWORD=P05tgr3s/pw
    command: [ "npm", "run", "start:docker_debug" ]
    depends_on:
      - db